### ISSUE TITLE
[DEVICE-ENV-SPECIFIC] 点击启动后，屏幕会出现以下图片，然后就退出了，无法进入。After clicking start, the following image will appear on the screen, and then exit without being able to enter

### ISSUE THREAD

**Issue by SynTaozi** [sipsuru/fiddler-everywhere-patch-automated#11]
![微信图片_20241113180651](https://github.com/user-attachments/assets/98c5da5b-5e5d-48a8-a5bc-2c1e79fc4c8e)

**Comment by sipsuru** [comment]
Sorry, but could not reproduce at all. Works well for others, so I guess it's a device specific issue. So we need information on your device.

What we want.
 - Fiddler Everywhere log file.
 - OS Version (For ex: Windows 11 Enterprise 23H2 build 22631.4317)
 - Installed security software / malware guard other than Windows Security (formely Windows Defender)
 - Default Browser name and version [Ex: Google Chrome 130.0.6723.117 (Official Build) (64-bit)]
 - A screen-record of you reproducing the bug (Because it's assumed device-specific)
 - Etc. every applicable.
 
 ---
 
 抱歉，我们无法重现问题。对于其他用户来说，它运行良好，所以我猜这是一个设备特定的问题。因此，我们需要您设备的信息。

我们需要的信息：

Fiddler Everywhere 日志文件。
 - 操作系统版本（例如：Windows 11 Enterprise 23H2 build 22631.4317）。
 - 除了 Windows 安全中心（以前称为 Windows Defender）之外安装的安全软件/恶意软件防护软件。
 - 默认浏览器的名称和版本 [例如：Google Chrome 130.0.6723.117（正式版）（64 位）]。
 - 您重现该错误的屏幕录制（因为假设这是设备特定的问题）。
 - 其他适用信息。

**Comment by sipsuru** [comment]
You can access them here: %APPDATA%\Fiddler Everywhere\Logs

**Comment by ChetWei** [comment]
same   situation
[netcore.log](https://github.com/user-attachments/files/17743136/netcore.log)
[electron.log](https://github.com/user-attachments/files/17743137/electron.log)
[cleanup.log](https://github.com/user-attachments/files/17743140/cleanup.log)

**Comment by sipsuru** [comment]
You too cannot start the server just like #7 #5 . But we couldn't find a reason yet.

Can you try these? So we can understand what's causing this issue:
  - **Most Importantly, checkout if port number `5678` is free** (Because msojocs server starts in this port of localhost. (If this's the cause you're lucky)
  
If the port is free then you have to try these: 
  - Disable every security/malware software and run the software. (In this cause a third party software has been blocking msojocs server).
  - Try to run in another Computer (In this cause it's indeed your system-environment-soecific)
  - Run in a virtual machine (In this cause it's indeed your system-environment-soecific)

---

你也无法启动服务器，就像 #7 和 #5 一样。但是我们还没找到原因。

可以试试以下步骤，帮助我们了解问题的原因：

  - **最重要的是，检查端口号 5678 是否空闲**（因为 msojocs 服务器在本地的这个端口启动。如果这是原因，那你很幸运）
  
如果端口是空闲的，请尝试以下操作：

  - 禁用所有安全/恶意软件并运行程序。（在这种情况下，可能是第三方软件阻止了 msojocs 服务器）
  - 在另一台计算机上运行程序。（在这种情况下，问题可能是你的系统环境特定的）
  - 在虚拟机中运行程序。（在这种情况下，问题可能是你的系统环境特定的）

**Comment by sipsuru** [comment]
Hmm. No info --means--> no identifying --means--> no investigation --means--> no solution.

**Comment by kawakaze-mirai** [comment]
same problem
OS: Windows 11 24H2
Fiddler Everywhere 6.0.0
logs:
[electron.log](https://github.com/user-attachments/files/18250196/electron.log)
[cleanup.log](https://github.com/user-attachments/files/18250197/cleanup.log)

**Comment by sipsuru** [comment]
You need to check if this happens **WITHOUT Patch**. Means you need to try install and open Fiddler Everywhere Official non-patched version.

In Fiddler Everywhere Documentation; it says:
> Ensure that Fiddler Everywhere's proxy port is open and unrestricted by a firewall/security tool. The default port is 8866, but you can change it from Settings > Connections > Fiddler listens on port.

It seems like Fiddler Everywhere's proxy port is restricted by any of your security/firewall tool.  
(It doesn't seems to be closed/already-in-use port error because every port it tries fails.)

Again; un-related to Patch.

---

Please let me know if you could install non-patched version and run it without errors first.

**Comment by sipsuru** [comment]
You need to check if this happens **WITHOUT Patch**. Means you need to try install and open Fiddler Everywhere Official non-patched version.

In [Fiddler Everywhere  Documentation -> Prerequiements](https://docs.telerik.com/fiddler-everywhere/installation-and-setup/quickstart-windows#prerequisites); it says:
> Ensure that Fiddler Everywhere's proxy port is open and unrestricted by a firewall/security tool. The default port is 8866, but you can change it from Settings > Connections > Fiddler listens on port.

It seems like Fiddler Everywhere's proxy port is restricted by any of your security/firewall tool.  
(It doesn't seems to be closed/already-in-use port error because every port it tries fails.)

Again; un-related to Patch.

---

Please let me know if you could install non-patched version and run it without errors first. 


---


你需要检查这是否在未打补丁的情况下发生。这意味着你需要尝试安装并打开官方的未打补丁版本的 Fiddler Everywhere。

在 [Fiddler Everywhere 文档 -> 先决条件](https://docs.telerik.com/fiddler-everywhere/installation-and-setup/quickstart-windows#prerequisites) 中提到：

> 确保 Fiddler Everywhere 的代理端口是开放的，且未被防火墙/安全工具限制。默认端口是 8866，但你可以在设置 > 连接 > Fiddler 监听的端口中进行更改。

看起来 Fiddler Everywhere 的代理端口被某些安全工具或防火墙限制了。
（这似乎并不是端口关闭或已被占用的错误，因为每个尝试的端口都失败了。）

再次强调，这与补丁无关。

请告知我是否可以成功安装未打补丁的版本并在没有错误的情况下运行。

**Comment by SC0624a** [comment]
> 您可以在这里访问它们。： %APPDATA%\Fiddler Everywhere\Logs
> 
> 您可以在此处访问它们：%APPDATA%\Fiddler Everywhere\Logs


[cleanup.log](https://github.com/user-attachments/files/18266184/cleanup.log)
[electron.log](https://github.com/user-attachments/files/18266185/electron.log)
[netcore.log](https://github.com/user-attachments/files/18266186/netcore.log)

问题相同
